issues:
  exclude-dirs:
    - docs
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Defaults above ours below
  presets:
    - bugs
    - performance
#linters-settings:
#  errcheck:
#    check-type-assertions: true
run:
  issues-exit-code: 1
  tests: false
  timeout: 10m
